---
name: autohotkey2-lsp
description: |
  AutoHotkey v2 Language support for VS Code, features realization based on v2 syntax analysis. Supports running on the Web, such as Chrome/Edge.
homepage: https://github.com/thqby/vscode-autohotkey2-lsp
licenses:
  - MIT
languages:
  - autohotkey
categories:
  - LSP
  - autohotkey
  - node
source:
  id: pkg:openvsx/thqby/vscode-autohotkey2-lsp@3.0.3
  download:
    file: thqby.vscode-autohotkey2-lsp-3.0.3.vsix
bin:
  autohotkey2-lsp: node:extension/dist/server.js
neovim:
  lspconfig: autohotkey_lsp
