---
name: jls
description: Java language server using Java compiler API, optimized for Neovim.
homepage: https://github.com/idelice/jls
licenses:
  - MIT
languages:
  - Java
categories:
  - LSP
  - DAP

source:
  id: pkg:github/idelice/jls@v0.5.1
  supported_platforms:
    - darwin_arm64
    - linux_x64_gnu
    - win_x64
  asset:
    - target: darwin_arm64
      file:
        - jls-macos-aarch64.tar.gz
        - jls-macos-aarch64.tar.gz.sha256
      lsp: lang_server_mac.sh
      dap: debug_adapter_mac.sh
    - target: linux_x64_gnu
      file:
        - jls-linux-x64.tar.gz
        - jls-linux-x64.tar.gz.sha256
      lsp: lang_server_linux.sh
      dap: debug_adapter_linux.sh
    - target: win_x64
      file:
        - jls-windows-x64.zip
        - jls-windows-x64.zip.sha256
      lsp: lang_server_windows.cmd
      dap: debug_adapter_windows.cmd

bin:
  jls: "{{source.asset.lsp}}"
  jls-debug-adapter: "{{source.asset.dap}}"
