---
name: statix
description: lints and suggestions for the nix programming language
homepage: https://github.com/oppiliappan/statix
licenses:
  - MIT
languages:
  - nix
categories:
  - Linter

source:
  id: pkg:cargo/statix@4.8.3

bin:
  statix: cargo:statix

neovim:
  lspconfig: statix
