---
name: clpp
description: CL++ compiler — a C++-inspired language that compiles to Luau.
homepage: https://kartzrbx.github.io/CLPP/
licenses:
  - MIT
languages:
  - CL++
  - Luau
categories:
  - Compiler

source:
  # renovate:datasource=github-tags
  id: pkg:cargo/clpp@v0.3.3?repository_url=https://github.com/KartzRbx/CLPP

bin:
  clpp: cargo:clpp
