---
name: clpp
description: CL++ compiler — a C++-inspired language that compiles to Luau.
homepage: https://kartzrbx.github.io/CLPP/
licenses:
  - MIT
languages:
  - CL++
  - Luau
categories:
  - Compiler

source:
  # renovate:datasource=github-releases
  id: pkg:github/KartzRbx/CLPP@v0.3.3
  asset:
    - target: win_x64
      file: clpp.exe
      bin: clpp.exe

bin:
  clpp: "{{source.asset.bin}}"
