---
name: teal-language-server
description: A language server for Teal, a typed dialect of Lua.
homepage: https://github.com/teal-language/teal-language-server
licenses:
  - MIT
languages:
  - Teal
categories:
  - LSP

source:
  id: pkg:luarocks/teal-language-server@0.1.3-1

bin:
  teal-language-server: luarocks:teal-language-server

neovim:
  lspconfig: teal_ls
