---
name: marko-language-server
description: A language server (implementing the language server protocol) for Marko.
homepage: https://github.com/marko-js/language-server
licenses:
  - MIT
languages:
  - Marko
categories:
  - LSP

source:
  id: pkg:npm/@marko/language-server@3

bin:
  marko-language-server: node_modules/.bin/marko-language-server

neovim:
  lspconfig: marko-js
