---
name: typescript-language-server
description: TypeScript & JavaScript Language Server.
homepage: https://github.com/typescript-language-server/typescript-language-server
licenses:
  - MIT
languages:
  - TypeScript
  - JavaScript
categories:
  - LSP

source:
  id: pkg:npm/typescript-language-server@5.3.0
  extra_packages:
    # The latest TS 7 removed lib/tsserver.js which is required by ts_ls.
    # See: https://github.com/mason-org/mason-registry/issues/15985
    - "typescript@6.0.3"

schemas:
  lsp: vscode:https://raw.githubusercontent.com/microsoft/vscode/main/extensions/typescript-language-features/package.json

bin:
  typescript-language-server: npm:typescript-language-server

neovim:
  lspconfig: ts_ls
