---
name: tombi
description: |
  TOML Formatter / Linter / Language Server
homepage: https://github.com/tombi-toml/tombi
licenses:
  - MIT
languages:
  - TOML
categories:
  - Formatter
  - Linter
  - LSP

neovim:
  lspconfig: tombi

source:
  id: pkg:github/tombi-toml/tombi@v0.11.0
  asset:
    - target: darwin_x64
      file: tombi-cli-{{ version | strip_prefix "v" }}-x86_64-apple-darwin.tar.gz
      bin: tombi-cli-{{ version | strip_prefix "v" }}-x86_64-apple-darwin/tombi
    - target: darwin_arm64
      file: tombi-cli-{{ version | strip_prefix "v" }}-aarch64-apple-darwin.tar.gz
      bin: tombi-cli-{{ version | strip_prefix "v" }}-aarch64-apple-darwin/tombi
    - target: linux_x64
      file: tombi-cli-{{ version | strip_prefix "v" }}-x86_64-unknown-linux-musl.tar.gz
      bin: tombi-cli-{{ version | strip_prefix "v" }}-x86_64-unknown-linux-musl/tombi
    - target: linux_arm64
      file: tombi-cli-{{ version | strip_prefix "v" }}-aarch64-unknown-linux-musl.tar.gz
      bin: tombi-cli-{{ version | strip_prefix "v" }}-aarch64-unknown-linux-musl/tombi
    - target: linux_armv7_gnu
      file: tombi-cli-{{ version | strip_prefix "v" }}-arm-unknown-linux-gnueabihf.tar.gz
      bin: tombi-cli-{{ version | strip_prefix "v" }}-arm-unknown-linux-gnueabihf/tombi
    - target: win_x64
      file: tombi-cli-{{ version | strip_prefix "v" }}-x86_64-pc-windows-msvc.zip
      bin: tombi.exe
    - target: win_arm64
      file: tombi-cli-{{ version | strip_prefix "v" }}-aarch64-pc-windows-msvc.zip
      bin: tombi.exe

bin:
  tombi: "{{source.asset.bin}}"
