---
name: ctags-lsp
description: A simple LSP server wrapping universal-ctags. Provides code completion, go-to-definition, and document/workspace symbols.
homepage: https://github.com/netmute/ctags-lsp
licenses:
  - MIT
languages: []
categories:
  - LSP

source:
  id: pkg:github/netmute/ctags-lsp@v0.11.0
  asset:
    - target: darwin_arm64
      file: ctags-lsp_Darwin_arm64.tar.gz
      bin: ctags-lsp
    - target: darwin_x64
      file: ctags-lsp_Darwin_x86_64.tar.gz
      bin: ctags-lsp
    - target: linux_arm64
      file: ctags-lsp_Linux_arm64.tar.gz
      bin: ctags-lsp
    - target: linux_x64
      file: ctags-lsp_Linux_x86_64.tar.gz
      bin: ctags-lsp
    - target: win_arm64
      file: ctags-lsp_Windows_arm64.zip
      bin: ctags-lsp.exe
    - target: win_x64
      file: ctags-lsp_Windows_x86_64.zip
      bin: ctags-lsp.exe

bin:
  ctags-lsp: "{{source.asset.bin}}"

neovim:
  lspconfig: ctags_lsp
