---
name: iferr
description: Go tool to generate if err != nil block for the current function.
homepage: https://github.com/koron/iferr
licenses:
  - MIT
languages:
  - Go
categories: []

source:
  id: pkg:golang/github.com/koron/iferr@v1.0.0

bin:
  iferr: golang:iferr
