---
name: matlab-language-server
description: Language Server Protocol implementation for the MATLAB language.
homepage: https://github.com/mathworks/MATLAB-language-server
licenses:
  - MIT
languages:
  - Matlab
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/mathworks/MATLAB-language-server@19438c8fbc02bdb8bb3bfd1eb17dbc8f39355fbd
  build:
    run: |
      npm install
      npm run package

bin:
  matlab-language-server: node:out/index.js

neovim:
  lspconfig: matlab_ls
